### ISSUE TITLE
Argument Error Invalid log level 

### ISSUE THREAD

**Issue by mansoorelahi** [logdna/ruby#24] opened 2020-02-20 20:15 UTC
There seems to be some issue with the library when used as 
config.logger = Logdna::Ruby.new("key", options={} ) as per the README its showing the below error
.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:284:in `level=': invalid log level:  (ArgumentError)

**Comment by mansoorelahi** [comment] 2020-02-21 08:42
Any update on it @vilyapilya  should we write a custom error handler and ditch the rails supports ?

**Comment by vilyapilya** [comment] 2020-02-24 21:12
@mansoorelahi  can you please give us more information on how you use the logger in your code?

**Comment by vilyapilya** [comment] 2020-02-25 00:58
@mansoorelahi  Actually I see what the issue is. I was able to reproduce it. Ruby just tries to use its own logger and initialize the Logger class and does not really reassign config.logger. Try to use a different name instead of 'logger'. For example 
`config.logdnaLogger = Logdna::Ruby.new(key, options)`

and then you can use it in your application like so : 
`Rails.configuration.logdnaLogger.log("my log message")`

**Comment by vidurangaw** [comment] 2020-03-04 21:14
@vilyapilya 
Same happens to me, but the workaround you provided us is not good for us. 

We basically need to replace the default logger with logdna so it captures all the logs. Could you please look into this? Thanks!

**Comment by vilyapilya** [comment] 2020-03-06 20:24
@mansoorelahi , @vidurangaw  we will release the fix next week.

**Closed** 2020-03-06 21:27 UTC
Labels: bug

**Comment by vilyapilya** [comment] 2020-03-13 21:04
@mansoorelahi , @vidurangaw the fix is in the v1.4.1
